version: '3.3'

services:
  client:
    build: ./Client
    ports:
      - "3000:3000"
    container_name: bamboo_restaurant-client
    restart: always
    environment:
      REACT_APP_API_URL: http://127.0.0.1:8080/
    depends_on:
      - server
    networks:
      - frontend

  server:
    build: ./Server
    ports:
      - "8080:8080"
    container_name: bamboo_restaurant-server
    restart: always
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bamboo_restaurant?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin 
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend  
  
  db:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    container_name: bamboo_restaurant-db
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bamboo_restaurant
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend 

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:  